spring.application.name=modificacion

spring.datasource.url=jdbc:mysql://localhost:3306/db_multigacha_modificacion_vm
spring.datasource.username=root
spring.datasource.password=
server.port=8088

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
