spring.application.name=contactos

spring.datasource.url=jdbc:mysql://localhost:3301/db_multigacha_contacto_vm
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true